"""SatDiff — Gradio app, deploys to Hugging Face Spaces.

Serving is deliberately separate from training: this loads finished weights
from the Hub and never trains anything.

Every returned image carries a visible watermark and PNG tEXt provenance
metadata. Both are product requirements, not decoration — synthetic satellite
imagery has a real misuse surface (fabricated disaster or infrastructure
imagery), and these are the two cheapest mitigations that survive a download.
"""
import os
import tempfile
import time
from pathlib import Path

# `spaces` MUST be imported before torch or anything else that touches CUDA —
# it raises outright if a CUDA context already exists. That is why this sits
# above the other third-party imports instead of in alphabetical order.
# It only exists on Spaces; locally, fall back to a no-op decorator so the same
# file runs unchanged on a laptop.
try:
    import spaces

    gpu = spaces.GPU(duration=60)
except ImportError:                                    # pragma: no cover
    def gpu(fn):
        return fn

import gradio as gr
import torch
from diffusers.training_utils import EMAModel
from huggingface_hub import hf_hub_download
from PIL import Image, ImageDraw, ImageFont
from PIL.PngImagePlugin import PngInfo

from satdiff.data import denormalize
from satdiff.model import build_model, build_schedulers
from satdiff.sample import sample

REPO_ID = "shairaam/satdiff-v1"
MODEL_VERSION = "satdiff-v1 (epoch 100)"

# Sorted directory names, matching the label order make_splits.py assigned.
CLASSES = [
    "AnnualCrop", "Forest", "HerbaceousVegetation", "Highway", "Industrial",
    "Pasture", "PermanentCrop", "Residential", "River", "SeaLake",
]

# Native output is 64x64. Displayed and downloaded at 4x via nearest-neighbour,
# which duplicates pixels exactly — no interpolation, no invented detail — so
# the watermark has room to be legible. Every original pixel is still recoverable.
UPSCALE = 4

OUT_DIR = Path(tempfile.gettempdir()) / "satdiff_out"
OUT_DIR.mkdir(exist_ok=True)


# --------------------------------------------------------------- model load

def load():
    """Load once at import. On ZeroGPU the model stays on CPU here and moves to
    GPU inside the decorated function; there is no CUDA context at startup."""
    ck = torch.load(hf_hub_download(REPO_ID, "last.pt"),
                    map_location="cpu", weights_only=False)
    cfg = ck["config"]
    model = build_model(cfg)
    model.load_state_dict(ck["model"])

    # Evaluate with the EMA weights. Samples are markedly worse without them.
    ema = EMAModel(model.parameters(), decay=cfg["train"]["ema_decay"])
    ema.load_state_dict(ck["ema"])
    ema.copy_to(model.parameters())

    model.eval()
    _, ddim = build_schedulers(cfg)
    return model, ddim, cfg


MODEL, DDIM, CFG = load()


# ------------------------------------------------------------ output safety

def watermark(img: Image.Image) -> Image.Image:
    """Visible 'AI-GENERATED' tag, bottom-right, with a dark plate behind it so
    it stays readable over both bright rooftops and dark water."""
    img = img.convert("RGB")
    draw = ImageDraw.Draw(img, "RGBA")
    text = "AI-GENERATED"
    try:
        font = ImageFont.truetype("DejaVuSans-Bold.ttf", 11)
    except OSError:
        font = ImageFont.load_default()

    x0, y0, x1, y1 = draw.textbbox((0, 0), text, font=font)
    tw, th = x1 - x0, y1 - y0
    pad = 3
    px = img.width - tw - pad * 2
    py = img.height - th - pad * 2
    draw.rectangle([px, py, img.width, img.height], fill=(0, 0, 0, 150))
    draw.text((px + pad - x0, py + pad - y0), text, font=font, fill=(255, 255, 255, 235))
    return img


def save_png(img: Image.Image, class_name: str, seed: int, idx: int) -> str:
    """Write with tEXt provenance. Metadata survives a download; a screenshot
    strips it, which is exactly why the visible watermark is there too."""
    meta = PngInfo()
    meta.add_text("AI-generated", "true")
    meta.add_text("Software", MODEL_VERSION)
    meta.add_text("Model", REPO_ID)
    meta.add_text("Class", class_name)
    meta.add_text("Seed", str(seed))
    meta.add_text("Created", time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()))
    meta.add_text("Comment",
                  "Synthetic image generated by a diffusion model. Not a real "
                  "Earth observation. Depicts no actual location.")

    path = OUT_DIR / f"satdiff_{class_name}_{seed}_{idx}.png"
    img.save(path, "PNG", pnginfo=meta)
    return str(path)


# ------------------------------------------------------------------ inference

@gpu
def generate(class_name: str, num_images: int, seed):
    if class_name not in CLASSES:
        raise gr.Error(f"Unknown class: {class_name}")
    num_images = int(num_images)

    seed = int(seed) if seed not in (None, "") else int(torch.randint(0, 2**31 - 1, (1,)))

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = MODEL.to(device)

    t0 = time.time()
    class_idx = CLASSES.index(class_name)
    batch = sample(model, DDIM, CFG, [class_idx] * num_images, device,
                   seed=seed, progress=False)
    elapsed = time.time() - t0

    paths = []
    for i, t in enumerate(denormalize(batch).cpu()):
        img = Image.fromarray((t.permute(1, 2, 0).numpy() * 255).astype("uint8"))
        img = img.resize((img.width * UPSCALE, img.height * UPSCALE), Image.NEAREST)
        paths.append(save_png(watermark(img), class_name, seed, i))

    note = (f"{num_images} × {class_name} · seed {seed} · {elapsed:.1f}s · "
            f"64×64 native, shown at {64 * UPSCALE}px")
    return paths, note


# ------------------------------------------------------------------------ UI

with gr.Blocks(title="SatDiff") as demo:
    gr.Markdown(
        "# SatDiff\n"
        "Class-conditional diffusion model generating synthetic 64×64 satellite "
        "tiles across 10 EuroSAT land-use classes.\n\n"
        "**These images are synthetic.** They are not real Earth observations "
        "and show no actual place. Every output is watermarked and carries "
        "provenance metadata. Do not present them as real imagery."
    )

    with gr.Row():
        with gr.Column(scale=1):
            cls = gr.Dropdown(CLASSES, value="Forest", label="Land-use class")
            n = gr.Slider(1, 8, value=4, step=1, label="Number of images")
            sd = gr.Number(label="Seed (blank = random)", value=None, precision=0)
            go = gr.Button("Generate", variant="primary")
        with gr.Column(scale=2):
            out = gr.Gallery(label="Generated", columns=4, height=380,
                             object_fit="contain")
            info = gr.Markdown()

    gr.Markdown(
        f"Weights: [`{REPO_ID}`](https://huggingface.co/{REPO_ID}) · "
        "Code: [github.com/DrKingSchultz69/satdiff-v2]"
        "(https://github.com/DrKingSchultz69/satdiff-v2)\n\n"
        "Test-split metrics: KID 0.0103 ± 0.0006, CAS 89.4%. "
        "PermanentCrop and AnnualCrop overlap in the source data and are the "
        "classes most often confused."
    )

    go.click(generate, [cls, n, sd], [out, info])

if __name__ == "__main__":
    # allowed_paths is required, not optional: gradio refuses to serve files
    # from arbitrary locations, and generate() writes its PNGs to OUT_DIR under
    # the system temp dir. Without this the Space starts fine and then fails
    # only when someone actually clicks Generate.
    demo.launch(allowed_paths=[str(OUT_DIR)])
